import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { promises as fs } from 'fs';
import path from 'path';
import Link from 'next/link';

import styles from '../styles/Home.module.css';

import Nav from '../src/components/ui/Nav';

interface Post {
  title: string;
  slug: string;
  date: string;
}

interface Props {
  postMetadata: Post[];
}

const Home: NextPage<Props> = ({ postMetadata }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />

      <main className={styles.main}>
        <h1 className={styles.title}>Posts</h1>

        {postMetadata.map((post) => {
          return (
            <div key={post.slug} style={{ backgroundColor: 'gray' }}>
              <Link href={`/posts/${post.slug}`}>{post.title}</Link>
            </div>
          );
        })}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  const postDirectory = path.join(process.cwd(), 'pages/posts');
  const postFilenames = await fs.readdir(postDirectory);

  const postModules = await Promise.all(
    postFilenames.map(async (p) => import(`./posts/${p}`))
  );

  const postMetadata = postModules.map((m) => m.metadata);

  return {
    props: {
      postMetadata,
    },
  };
};

export default Home;
